### ISSUE TITLE
Engine type is not public anymore

### ISSUE THREAD

**Issue by hilbertshotel** [0x9ef/openai-go#1]
For some reason the Engine type is no longer public and I can't pass it around functions. Was this change deliberate and if so, what am I missing?

**Comment by 0x9ef** [comment]
The Engines endpoints are deprecated. As written in the documentation:

> Please use their replacement, [Models](https://beta.openai.com/docs/api-reference/models), instead. [Learn more](https://help.openai.com/TODO).

If you want to provide a custom engine, use instead of this `Model` parameter to the request. 

Example with the "completion" request:
```
completionResp, err := e.Completion(ctx, &openai.CompletionOptions{
	Model: openai.ModelTextDavinci001, // model (engine)
}
```

**Comment by hilbertshotel** [comment]
Per documentation:

> To initialize engine, use this:  `e := openai.New(os.Getenv("OPENAI_KEY"))`

How can I pass this engine to functions if the type is not public? The Model type is just a string.

**Comment by 0x9ef** [comment]
> How can I pass this engine to functions if the type is not public? The Model type is just a string.

Fixed it, please try this now

**Comment by hilbertshotel** [comment]
Works perfect. Thank you.
